import os
a = ("Type Guest Hacker To Run Tool")
print (a)
a1 = input ("Type :")
if a1 == "Guest Hacker" :
  print ("Corect")
else:
  print ("Error..!")
os.system ("clear")
print ("██╗░░██╗░█████╗░░█████╗░██╗░░██╗")
print ("██║░░██║██╔══██╗██╔══██╗██║░██╔╝")
print ("███████║███████║██║░░╚═╝█████═╝")
print ("██╔══██║██╔══██║██║░░██╗██╔═██╗")
print ("██║░░██║██║░░██║╚█████╔╝██║░╚██╗")
print ("╚═╝░░╚═╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝")
ae = ("[1]Hack Tools")
af = ("[2]Exit")
print (ae)
print (af)
ad = input ("What U want?: ")
if ad == "1" :
  os.system ("clear")
  print ("FBTOOL")
  print ("SQLMAP")
  print ("RED HAWK")
  print ("IP TRACER")
  print ("Tool-X")
  print ("DarkFly")
  print ("Zphisher")
  print ("nexphisher")
  print ("v7x phishing")
  print ("EasY_HaCk")
  print ("onex")
  print ("host")
  print ("proxy finder")
  print ("metasploit")
  print ("nmap")
  print ("MBomb")
  print ("TBmob")
  print ("hammer")
  print ("xerxes")
  print ("Firecrack")
  print ("Admin Finder")
  print ("vbug")
  print ("ngrok")
  print ("Call")
  print ("get_proxy")
  print ("m-dork")
  print ("EmailHarvester")
  print ("bye")
  print ("in new verison i add new tools")
  ar = ("[1]exit")
  ar1 = ("[2]back")
  am = input ("//: ")
  if am == "1" :
    print ("ctrl+c")
  if am == "2" :
    a = ("Type Guest Hacker To Run Tool")
print (a)
a1 = input ("Type :")
if a1 == "Guest Hacker" :
  print ("Corect")
else:
  print ("Error..!")
os.system ("clear")
print ("██╗░░██╗░█████╗░░█████╗░██╗░░██╗")
print ("██║░░██║██╔══██╗██╔══██╗██║░██╔╝")
print ("███████║███████║██║░░╚═╝█████═╝")
print ("██╔══██║██╔══██║██║░░██╗██╔═██╗")
print ("██║░░██║██║░░██║╚█████╔╝██║░╚██╗")
print ("╚═╝░░╚═╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝")
ae = ("[1]Hack Tools")
af = ("[2]Exit")
print (ae)
print (af)
ad = input ("What U want?: ")
    if ad == "2" :
  print ("ctrl+C")
